# Generated by Django 5.0.1 on 2024-02-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0003_tag_pet_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
